# Generated by Django 5.1.3 on 2024-11-24 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0002_post_author_post_date_post_time_alter_post_body_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
