# Generated by Django 5.1.3 on 2024-11-24 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0005_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
