# Generated by Django 5.1.3 on 2024-11-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0006_remove_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='time',
        ),
        migrations.AddField(
            model_name='post',
            name='endtime',
            field=models.TimeField(default='23:00'),
        ),
        migrations.AddField(
            model_name='post',
            name='starttime',
            field=models.TimeField(default='18:00'),
        ),
    ]
