# Generated by Django 5.1.3 on 2024-11-29 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0008_post_substitute_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='substitute',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='シフト交代者名'),
        ),
    ]
